version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serverless
    versions:
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.1
    - 2.25.2
    - 2.26.0
    - 2.27.1
    - 2.28.0
    - 2.28.5
    - 2.28.7
    - 2.29.0
    - 2.30.0
    - 2.30.3
    - 2.31.0
    - 2.32.1
    - 2.33.1
    - 2.34.0
    - 2.35.0
    - 2.36.0
    - 2.37.0
    - 2.37.2
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@material-ui/styles"
    versions:
    - 4.11.3
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: eslint-config-airbnb
    versions:
    - 18.0.1
