export const UPDATE_CALENDAR_URL = "UPDATE_CALENDAR_URL";
export const UPDATE_AION_CALENDAR_RESOURCE = "UPDATE_AION_CALENDAR_RESOURCE";
export const UPDATE_SUMMARY_INCLUDE_FILTER = "UPDATE_SUMMARY_INCLUDE_FILTER";
export const UPDATE_RSVP_ATTENDING = "UPDATE_RSVP_ATTENDING";
export const APP_LOADING = "APP_LOADING";
export const APP_LOADING_COMPLETED = "APP_LOADING_COMPLETED";
export const UPDATE_FILTER_ID = "UPDATE_FILTER_ID";
export const UPDATE_CALENDAR_ID = "UPDATE_CALENDAR_ID";
