export const UPDATE_SERIAL = "UPDATE_SERIAL";
export const UPDATE_AA_BATTERIES = "UPDATE_AA_BATTERIES";
export const UPDATE_D_BATTERIES = "UPDATE_D_BATTERIES";
export const UPDATE_PARALLEL_PORT = "UPDATE_PARALLEL_PORT";
export const UPDATE_STRIKES = "UPDATE_STRIKES";
